### ISSUE TITLE
docker build gdown errors 

### ISSUE THREAD

**Issue by biochunan** [biochunan/esmfold-docker-image#1]
**Describe the bug**
`gdown` failed downloading 

**To Reproduce**

```shell
docker build -t esmfold:test . 
```

**Expected behavior**
```shell
 => ERROR [18/21] RUN mkdir -p /home/vscode/.cache/torch/hub/checkpoints &&     gdown https://drive.google.com/uc?id=1lW8CVTSzX8bwLxbM8lAu_  0.9s
------                                                                                                                                            
 > [18/21] RUN mkdir -p /home/vscode/.cache/torch/hub/checkpoints &&     gdown https://drive.google.com/uc?id=1lW8CVTSzX8bwLxbM8lAu_qXQkrPZuSxA -O /home/vscode/.cache/torch/hub/checkpoints/esm2_t36_3B_UR50D-contact-regression.pt &&     gdown https://drive.google.com/uc?id=1CHTS2cB8HrgayylwVB8tsrLKcpTqKFLx -O /home/vscode/.cache/torch/hub/checkpoints/esm2_t36_3B_UR50D.pt &&     gdown https://drive.google.com/uc?id=1CQZdYpXI1pb55ro8hCEP37pMsG2_Dbul -O /home/vscode/.cache/torch/hub/checkpoints/esmfold_3B_v1.pt:
0.821 Traceback (most recent call last):
0.821   File "/home/vscode/.local/bin/gdown", line 8, in <module>
0.821     sys.exit(main())
0.821   File "/home/vscode/.local/lib/python3.10/site-packages/gdown/cli.py", line 156, in main
0.822     filename = download(
0.822   File "/home/vscode/.local/lib/python3.10/site-packages/gdown/download.py", line 259, in download
0.822     filename_from_url = m.groups()[0]
0.822 AttributeError: 'NoneType' object has no attribute 'groups'
------
Dockerfile:81
--------------------
  80 |     # use gdown to download above files from google drive 
  81 | >>> RUN mkdir -p /home/vscode/.cache/torch/hub/checkpoints && \
  82 | >>>     gdown https://drive.google.com/uc?id=1lW8CVTSzX8bwLxbM8lAu_qXQkrPZuSxA -O /home/vscode/.cache/torch/hub/checkpoints/esm2_t36_3B_UR50D-contact-regression.pt && \
  83 | >>>     gdown https://drive.google.com/uc?id=1CHTS2cB8HrgayylwVB8tsrLKcpTqKFLx -O /home/vscode/.cache/torch/hub/checkpoints/esm2_t36_3B_UR50D.pt && \
  84 | >>>     gdown https://drive.google.com/uc?id=1CQZdYpXI1pb55ro8hCEP37pMsG2_Dbul -O /home/vscode/.cache/torch/hub/checkpoints/esmfold_3B_v1.pt
  85 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c mkdir -p /home/vscode/.cache/torch/hub/checkpoints &&     gdown https://drive.google.com/uc?id=1lW8CVTSzX8bwLxbM8lAu_qXQkrPZuSxA -O /home/vscode/.cache/torch/hub/checkpoints/esm2_t36_3B_UR50D-contact-regression.pt &&     gdown https://drive.google.com/uc?id=1CHTS2cB8HrgayylwVB8tsrLKcpTqKFLx -O /home/vscode/.cache/torch/hub/checkpoints/esm2_t36_3B_UR50D.pt &&     gdown https://drive.google.com/uc?id=1CQZdYpXI1pb55ro8hCEP37pMsG2_Dbul -O /home/vscode/.cache/torch/hub/checkpoints/esmfold_3B_v1.pt" did not complete successfully: exit code: 1
```

**Screenshots**
<img width="1159" alt="image" src="https://github.com/biochunan/esmfold-docker-image/assets/29458139/53919697-f4c1-4a01-9d6b-7b06a9730763">

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 22.04

**Comment by biochunan** [comment]
Installing the latest version of `gdown` (v5.0.1) solved this issue.
