### ISSUE TITLE
torch undefined symbol: iJIT_NotifyEvent error 

### ISSUE THREAD

**Issue by biochunan** [biochunan/esmfold-docker-image#3]
**Describe the bug**
Received the following error when executing `esm-fold` using the image 

```sh
# on the host machine
> % docker run --rm $USER/esmfold:test -h 
Traceback (most recent call last):
  File "/home/vscode/.conda/envs/py39-esmfold/bin/esm-fold", line 5, in <module>
    from esm.scripts.fold import main
  File "/home/vscode/.conda/envs/py39-esmfold/lib/python3.9/site-packages/esm/__init__.py", line 8, in <module>
    from .data import Alphabet, BatchConverter, FastaBatchedDataset  # noqa
  File "/home/vscode/.conda/envs/py39-esmfold/lib/python3.9/site-packages/esm/data.py", line 12, in <module>
    import torch
  File "/home/vscode/.conda/envs/py39-esmfold/lib/python3.9/site-packages/torch/__init__.py", line 202, in <module>
    from torch._C import *  # noqa: F403
ImportError: /home/vscode/.conda/envs/py39-esmfold/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent
```

which looks like torch installation problem

**To Reproduce**

Start the container 

```sh 
docker run --rm -it --entrypoint zsh $USER/esmfold:base 
```

Then inside the container

```sh
> conda activate py39-esmfold
(py39-esmfold) > python -c 'import torch'
```

**Expected behavior**

Expected to receive the same error: 

```sh
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vscode/.conda/envs/openfold-venv/lib/python3.9/site-packages/torch/__init__.py", line 202, in <module>
    from torch._C import *  # noqa: F403
ImportError: /home/vscode/.conda/envs/openfold-venv/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Additional context**

**Comment by biochunan** [comment]
fixed in v0.0.2
