### ISSUE TITLE
No NVIDIA Drivers

### ISSUE THREAD

**Issue by DrLeucine** [biochunan/esmfold-docker-image#7]
**Describe the bug**
When I use the docker containers from Docker Hub it seems like the GPU is not loaded

**To Reproduce**

```bash
(base) s1622572@aspartate:~$ docker run --rm  -v /scratch/timed_dataset/protease/final_fasta/TIMED_charge_temp_0.2_n_1000_13resdel_relaxed_Con1A_conserved.fasta:/home/vscode/input/input.fasta -v /scratch/timed_dataset/protease/final_fasta/:/home/vscode/output biochunan/esmfold-image:root-devel -i /home/vscode/input/input.fasta -o /home/vscode/output/
24/05/14 12:38:12 | INFO | root | Reading sequences from /home/vscode/input/input.fasta
24/05/14 12:38:12 | INFO | root | Loaded 1000 sequences from /home/vscode/input/input.fasta
24/05/14 12:38:12 | INFO | root | Loading model
Traceback (most recent call last):
  File "/miniconda/envs/py39-esmfold/bin/esm-fold", line 8, in <module>
    sys.exit(main())
  File "/miniconda/envs/py39-esmfold/lib/python3.9/site-packages/esm/scripts/fold.py", line 202, in main
    run(args)
  File "/miniconda/envs/py39-esmfold/lib/python3.9/site-packages/esm/scripts/fold.py", line 155, in run
    model.cuda()
  File "/miniconda/envs/py39-esmfold/lib/python3.9/site-packages/torch/nn/modules/module.py", line 689, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/miniconda/envs/py39-esmfold/lib/python3.9/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/miniconda/envs/py39-esmfold/lib/python3.9/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/miniconda/envs/py39-esmfold/lib/python3.9/site-packages/torch/nn/modules/module.py", line 602, in _apply
    param_applied = fn(param)
  File "/miniconda/envs/py39-esmfold/lib/python3.9/site-packages/torch/nn/modules/module.py", line 689, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/miniconda/envs/py39-esmfold/lib/python3.9/site-packages/torch/cuda/__init__.py", line 217, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

**Expected behavior**
Using NVIDIA drivers

**Screenshots**

**Desktop (please complete the following information):**
NVIDIA-SMI 450.119.03   Driver Version: 450.119.03   CUDA Version: 11.0

**Comment by biochunan** [comment]
Hi @universvm, thanks for raising the issue.  

Can you try the following: 
- Try to add `--gpus all` to your command. This should enable GPU access for the container;
- Try to mount volumes to the `root` inside the container because you are using the root version. Apologies that I didn't emphasize this on the README page. Example script is provided at [run-root-devel.sh](https://github.com/biochunan/esmfold-docker-image/blob/main/example/scripts/run-root-devel.sh)

I've included a modified command for you. Let me know if this helps. Thanks!

```shell 
docker run --rm  \
--gpus all \
-v /scratch/timed_dataset/protease/final_fasta/TIMED_charge_temp_0.2_n_1000_13resdel_relaxed_Con1A_conserved.fasta:/root/input/input.fasta \
-v /scratch/timed_dataset/protease/final_fasta/:/root/output \
biochunan/esmfold-image:root-devel \
-i /root/input/input.fasta \
-o /root/output/
```
